Databases-week3
Yuliia-Balandiuk/hyf-homework pull request #18
Opened 2022-09-03 17:10 UTC by Yuliia-Balandiuk

2022-09-04 22:24 UTC, Elia-Git requested changes
Pls pay extra attention where you should use parenthesis and where you don't ...
For instance below code is correct but doesn't run in VS code as you use parenthesis where you shouldn't.

**SELECT  `meal`.`id`, `meal`.`title`, AVG(`review`.`stars`)
FROM `meal`
INNER JOIN `review` ON `meal`.`id` = `review`.`meal_id`
GROUP BY `meal_id`
ORDER BY AVG(`review`.`stars`) DESC;**

2022-09-04 22:24 UTC, Elia-Git commented on databases/week3/mealsharing_db.sql
> +);
Good job.

2022-09-04 22:24 UTC, Elia-Git commented on databases/week3/queries.sql
> +FROM `meal`;
Why parenthesis around table name when quering ...? Remove all parenthesis where you use it around table name
for instance in lines. 2,6.8,12,15 etc

2022-09-04 22:24 UTC, Elia-Git commented on databases/week3/queries.sql
> +ORDER BY `reservation`.`created_date`;
Try this instead. I would also recommend you to include a line of what the task is (question for each solution). Here for instance
**-- Get reservations for a specific meal sorted by created_date**
```
SELECT meal.description,reservation.created_date AS reservation_Created_date
FROM meal
JOIN reservation ON meal.id = reservation.meal_id
where meal_id=3
ORDER BY reservation.created_date ASC;
```

2022-09-13 08:46 UTC, viedamayanti commented on databases/week3/mealsharing_db.sql
> +VALUES (1, 'Crawfish soup', 'Traditional soup cooked on crawfish tails. Served with homemade dumplings with crayfish necks', 'Bregnegaardsvej 2A, 2920 Charlottenlund', '2022-08-01 10:00:00', 2, 250.5
The id is auto increment, so you don't need to write it manually, sql will do it

2022-09-28 14:47 UTC, merged